# Generated by Django 4.2.27 on 2025-12-26 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0136_tool__requires_area_occupancy_minimum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='_adjustment_request_reviewers',
            field=models.ManyToManyField(blank=True, db_table='tool_adjustment_request_reviewers', help_text='Users who can approve/deny adjustment requests for this tool. Defaults to facility managers if left blank.', related_name='adjustment_request_reviewer_on_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tool',
            name='_backup_owners',
            field=models.ManyToManyField(blank=True, db_table='tool_backup_owners', help_text='Alternate staff members who are responsible for administration of this tool when the primary owner is unavailable.', related_name='backup_for_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tool',
            name='_staff',
            field=models.ManyToManyField(blank=True, db_table='tool_staff', help_text='Users who can act as staff for this tool.', related_name='staff_for_tools', to=settings.AUTH_USER_MODEL, verbose_name='Act as staff'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='_superusers',
            field=models.ManyToManyField(blank=True, db_table='tool_superusers', help_text='Superusers who can train users on this tool.', related_name='superuser_for_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['tree_id', 'lft'], name='NEMO_area_tree_id_lft_idx'),
        ),
        migrations.AlterModelTable(
            name='qualification',
            table='user_qualifications',
        ),
    ]
