apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql
data:
  my.cnf: |
    [mysqld]
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    max_connections = 500
    sql_mode = STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    default-time-zone = '+00:00'

    [client]
    default-character-set = utf8mb4
